# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'build/**'
      - 'tests/**'
      - 'trimnami/**'
      - 'setup.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'build/**'
      - 'tests/**'
      - 'trimnami/**'
      - 'setup.py'

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      # Setup env
      - uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Test and generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          export AR=/usr/bin/ar
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest coverage
          python -m pip install .
          coverage run -m pytest
